name: giveEmerald
version: 0.0.1
main: halinezumi\giveEmerald\Main
api: 4.5.1
src-namespace-prefix: halinezumi\giveEmerald
commands:
  test:
    description: "test command"
    usage: "/test"
    permission: emeraldexplose.prepare
  shuffle:
    description: "shuffle number of emerald"
    usage: "/shuffle"
    permission: emeraldexplose.prepare

permissions:
  emeraldexplose.prepare:
    default: op