name: emeraldExplose
version: 0.0.1
main: halinezumi\emeraldExplose\Main
api: 4.5.1
src-namespace-prefix: halinezumi\emeraldExplose
commands:
  test:
    description: "test command"
    usage: "/test"
    permission: emeraldexplose.prepare
  shuffle:
    description: "shuffle number of emerald"
    usage: "/shuffle"
    permission: emeraldexplose.prepare
  outputshuffle:
    description: "output random number by using /shuffle"
    usage: "/outputshuffle"
    permission: emeraldexplose.prepare
  exchange_tnt:
    description: "get TNT with emerald"
    usage: "/exchange_tnt"
    permission: emeraldexplose.prepare
  pos:
    description: "output now position of command sender"
    usage: "/pos"
    permission: emeraldexplose.prepare
  game_start:
    description: "execute when game is started"
    usage: "/game_start"
    permission: emeraldexplose.prepare

permissions:
  emeraldexplose.prepare:
    default: op